apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: kubedeploy
  labels:
    app: krakend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: devopsfaith/krakend:2.7.1
        ports:
        - containerPort: 8000
          name: http
        command: ["krakend"]
        args: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
          readOnly: true
        livenessProbe:
          httpGet:
            path: /__health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /__health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
      initContainers:
      - name: wait-for-services
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - until nc -z user-service 8080 && nc -z payment-service 8081; do
            echo "Waiting for backend services...";
            sleep 2;
          done;
          echo "Backend services are ready!";
