apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kubedeploy
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: kubedeploy
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: kubedeploy
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-service
  namespace: kubedeploy
  labels:
    app: krakend
spec:
  type: LoadBalancer
  selector:
    app: krakend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  # AWS Load Balancer Controller annotations
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
